name: TASK_C Automated SAST using Semgrep

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  security-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
  
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and Export SARIF
        run: |
          semgrep scan \
            --config="p/owasp-top-ten" \
            --config="custom-rules.yml" \
            --sarif -o semgrep-report.sarif --error
      
      - name: Vulnerability Summary
        if: always() 
        run: |
          echo "### SARIF FINDINGS SUMMARY ###"
          jq -r '(.runs[0].results // []) | map(select(has("suppressions") | not)) | group_by(.ruleId) | sort_by(length) | reverse | .[] | "\(length) findings of: \(.[0].ruleId)"' semgrep-report.sarif
          echo "##############################"

      - name: Upload Semgrep Artifact
        uses: actions/upload-artifact@v6
        if: always() 
        with:
          name: semgrep-audit-report
          path: semgrep-report.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        if: always() 
        with:
          sarif_file: semgrep-report.sarif
